// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // La CLI Prisma (db push, migrate, seed, studio) utilise la connexion directe
    // (DIRECT_URL, port 5432) quand elle existe — meilleure pour les migrations que
    // le pooler transaction (6543). Repli sur DATABASE_URL si DIRECT_URL absent.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
